In [1]:
import pandas as pd
pred = pd.read_csv('new_dataset_predictions.csv',
                   sep='§', engine="python")
pred

                                                      text  prediction  label
0        "Former Florida Gators quarterback Tim Tebow w...         0.0    0.0
1        Florida Gators quarterback Tim Tebow waves as ...         0.0    0.0
2        Gators quarterback Tim Tebow waves as he stand...         0.0    0.0
3        quarterback Tim Tebow waves as he stands on th...         0.0    0.0
4        Tim Tebow waves as he stands on the sidelines ...         0.0    0.0
...                                                    ...         ...    ...
3773409  is left after its expiration." "The Islamic St...         0.0    0.0
3773410  left after its expiration." "The Islamic State...         0.0    0.0
3773411  after its expiration." "The Islamic States rec...         0.0    0.0
3773412  its expiration." "The Islamic States recent se...         0.0    0.0
3773413  expiration." "The Islamic States recent setbac...         0.0    0.0

[3773414 rows x 3 columns]

In [3]:
pred.query('prediction != label')

                                                      text  prediction  label
16247    Egyptair Airbus 320, which disappeared from ra...         1.0    0.0
16248    Airbus 320, which disappeared from radar over ...         1.0    0.0
16249    320, which disappeared from radar over the Med...         1.0    0.0
16250    which disappeared from radar over the Mediterr...         1.0    0.0
16251    disappeared from radar over the Mediterranean ...         1.0    0.0
...                                                    ...         ...    ...
3726288  company told the Huffington Post U.K. We have ...         1.0    0.0
3726289  told the Huffington Post U.K. We have a string...         1.0    0.0
3726290  the Huffington Post U.K. We have a stringent V...         1.0    0.0
3726291  Huffington Post U.K. We have a stringent Vende...         1.0    0.0
3726292  Post U.K. We have a stringent Vender Code of C...         1.0    0.0

[1076854 rows x 3 columns]