In [1]:
import pandas as pd
ds = pd.read_csv('../../CSVs/dataset_predictionsIntScore.csv', sep='§')
ds

C:\Users\gabre\AppData\Local\Temp\ipykernel_6524\3347707246.py:2: ParserWarning: Falling back to the 'python' engine because the separator encoded in utf-8 is > 1 char long, and the 'c' engine does not support such separators; you can avoid this warning by specifying engine='python'.
  ds = pd.read_csv('../../CSVs/dataset_predictionsIntScore.csv', sep='§')

                                                      text  score
0        "Former Florida Gators quarterback Tim Tebow w...    3.0
1        Florida Gators quarterback Tim Tebow waves as ...    3.0
2        Gators quarterback Tim Tebow waves as he stand...    3.0
3        quarterback Tim Tebow waves as he stands on th...    3.0
4        Tim Tebow waves as he stands on the sidelines ...    3.0
...                                                    ...    ...
3773409  is left after its expiration." "The Islamic St...    3.0
3773410  left after its expiration." "The Islamic State...    3.0
3773411  after its expiration." "The Islamic States rec...    3.0
3773412  its expiration." "The Islamic States recent se...    3.0
3773413  expiration." "The Islamic States recent setbac...    3.0

[3773414 rows x 2 columns]

In [3]:
samples = ds.sample(frac=0.05, random_state=1)
samples

                                                      text  score
3147554  shocked, as though you are surprised your chil...    3.0
3719728  of New Jersey began his career dabbling in eve...    3.0
536865   he told participants on the course, run by the...    3.0
1727468  % of readers think this story is Fact. Add you...    3.0
1670879  development of the exchange rate since the beg...    3.0
...                                                    ...    ...
2439013  view of Bush. White Evangelical Protestants fa...    3.0
221697   congregation of 30,000. The ministry, which ce...    3.0
2383405  to our own, and found Denmarks far superior. T...    3.0
1262393  an employee or job applicants worth. What make...   -1.0
3651869  to turn off the camera because she knew that w...    3.0

[188671 rows x 2 columns]

In [4]:
data = ds['text'].tolist()
label = ds['score'].tolist()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(ngram_range=(1, 3), min_df=2)
X = vectorizer.fit_transform(data)
X.shape

In [ ]:
# MLPR, SVR
from sklearn.model_selection import RandomizedSearchCV 
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
import time

start = time.time()


mlpr = MLPRegressor()
mlpr_params = {'hidden_layer_sizes': [(100,), (100, 100), (100, 200), (100, 100, 100)],
               'alpha': [0.0001, 0.001, 0.01, 0.1],
               'learning_rate': ['constant', 'invscaling', 'adaptive'],
               'learning_rate_init': [0.001, 0.01, 0.1, 0.5],
               'max_iter': [100, 200, 500, 1000],
               'tol': [0.0001, 0.001, 0.01, 0.1]}
rsMLPR = RandomizedSearchCV(mlpr, mlpr_params, n_iter=10, cv=5, scoring='neg_mean_squared_error', random_state=1)

svr = SVR()
svr_params = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [0.001, 0.01, 0.1, 1, 10],
              'kernel': ['linear', 'poly', 'rbf', 'sigmoid', 'precomputed'],
              'degree': [2, 3, 4, 5, 6],
              'coef0': [0.1, 0.2, 0.3, 0.4, 0.5],
              'shrinking': [True, False]}
rsSVR = RandomizedSearchCV(svr, svr_params, n_iter=10, cv=5, scoring='neg_mean_squared_error', random_state=1)

rsMLPR.fit(X, label)
print('Best params MLPR:\n' + rsMLPR.best_params_ + '\n')
print('Best score MLPR:\n' + rsMLPR.best_score_ + '\n')

rsSVR.fit(X, label)
print('Best params SVR:\n' + rsSVR.best_params_ + '\n')
print('Best score SVR:\n' + rsSVR.best_score_ + '\n')


print('Time elapsed: ' + str(((time.time() - start) / 60/ 60)) + ' hours')